### ISSUE TITLE
Install function erases existing repo data via _repo_add

### ISSUE THREAD

**Issue by calebj** [orels1/Red-Portal-Cogs#13]
Invoking `downloader._repo_add(name, url)` on an existing repo clears Installer's data on that repo, causing it to lose track of all installed cogs for purposes  of updates. See [here](https://github.com/Cog-Creators/Red-DiscordBot/blob/develop/cogs/downloader.py#L94-L95).

**Comment by orels1** [comment]
Thanks for the heads-up. I’ll try to fix that asap

**Comment by orels1** [comment]
So as I understand it - I should use `list_cogs` to check if the cog is available. and if so - install it with `install` or if not - use `_repo_add` as before

**Comment by calebj** [comment]
Perhaps. Personally, I think that it would be best to invoke the appropriate methods directly instead of going through `ctx.invoke`. But as long as it checks that it isn't overwriting anything, any approach that works is better than what it does now.
